name: build-publish-silicon

on: push

jobs:
  build:
    name: Build distribution 📦
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system packages
        run: brew install pkg-config lua@5.1 libzip qt5 capnp

      - name: Setup system
        run: echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile

      - name: debug
        run: echo $PATH

      - name: debug 2
        run: ls -la ~/

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
