name: build-publish-silicon

on: push

jobs:
  build:
    name: Build distribution 
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system packages
        run: ls -la
      #   run: brew install pkg-config lua@5.1 libzip qt5 capnp cmake

      # - name: Build project
      #   run: |
      #     export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"
      #     export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
      #     make -j$(sysctl hw.ncpu | cut -d: -f2) /Users/runner/work/stable-retro
      #     python3.10 -m pip install -v .

      # - name: Install packages
      #   run: python3.10 -m pip install --upgrade pip build wheel

      # - name: Build silicon wheel
      #   run: python -m build --wheel --sdist

      # - name: Test
      #   run: python -c "import retro"

      # - name: Test
      #   run: |
      #     python3.10 -m pip install --upgrade pip pytest
      #     pytest /Users/runner/work/stable-retro/stable-retro/tests/test_python

      # - name: Install pypa/build
      #   run: >-
      #     python3 -m
      #     pip install
      #     build
      #     --user
      # - name: Build a binary wheel and a source tarball
      #   run: python3 -m build
      # - name: Store the distribution packages
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: python-package-distributions
      #     path: dist/
